### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ChrisVent** [FlickerStudio/flickerjs#3]
1) The 404.pug file is unnecessary.  [commit](https://github.com/FlickerStudio/flickerjs/commit/86473b49f7c351d3d4ab05b18ed5140b58ffae5d)

2) If is discommented the favicon middleware and favicon.ico isn't in static dir, throw an exception. [commit](https://github.com/FlickerStudio/flickerjs/commit/5063642bb8aafd38417a687736063eec8519cf5b)

3) In res.json() -> should to use JSON.stringify(obj, null,  for print two spaces btw vars. [commit](https://github.com/FlickerStudio/flickerjs/commit/a8f443d0792eef2c29f6a249b8842e6d86e351a4)

4) create a flicker.log for log the calls to next(err). [commit](https://github.com/FlickerStudio/flickerjs/commit/09e8f1e394c883873aa782dddc5bf1e3ae10737e)

5)  rename some functions and delete a few of them in order to create most generalists fuctios that her first param is a JSON with the options.

5b) rename app.use to app.go: [commit](https://github.com/FlickerStudio/flickerjs/commit/3eb48cb947ebac8b07f5d92934d7210c1a1c978e)

```javascript
    app.to(
        {
            method: "GET",
            url:"/foo"
        },
         (req,res,next)  => {
             next();
         }
    );
```

6) Accept two middlewares in app.to()

Replacing this:
```javascript
App.to({ url:'/foo' },middleware)
    .to({ url:'/foo' },router)
```
With:
```javascript
App.to({ url:'/foo' }, middleware, router)
```

**Comment by flickerapps** [comment]
1) [commit](https://github.com/FlickerStudio/flickerjs/commit/86473b49f7c351d3d4ab05b18ed5140b58ffae5d)
2) [commit](https://github.com/FlickerStudio/flickerjs/commit/5063642bb8aafd38417a687736063eec8519cf5b)
3) [commit](https://github.com/FlickerStudio/flickerjs/commit/a8f443d0792eef2c29f6a249b8842e6d86e351a4)
4) Pending...*
5) In Proccess...*
5.b) [commit](https://github.com/FlickerStudio/flickerjs/commit/3eb48cb947ebac8b07f5d92934d7210c1a1c978e)

**Comment by flickerapps** [comment]
4) [commit](https://github.com/FlickerStudio/flickerjs/commit/09e8f1e394c883873aa782dddc5bf1e3ae10737e)

**Comment by ChrisVent** [comment]
Accept two middlewares in app.to()

Replacing this:
```javascript
App.to({ '/foo' },middleware)
    .to({ url:'/foo' },router)
```
With:
```javascript
App.to({ url:'/foo' }, middleware, router)
```
