### ISSUE TITLE
Nombre para el framework en español

### ISSUE THREAD

**Issue by flickerapps** [FlickerStudio/flickerjs#6]
Sugieran el nombre que mas les guste para la version hispana del framework.
Fork del proyecto --> [Aqui](https://github.com/flickerapps/flickerjs)

**Comment by ChrisVent** [comment]
Veloz.js

**Comment by flickerapps** [comment]
@reneolivo @ranfis @ADelRosarioH @rmariuzzo

**Comment by ADelRosarioH** [comment]
Flicker.js me gusta igual para la versión hispana.

**Comment by reneolivo** [comment]
Hola, de qué se trata ésto? No me han hablado de este proyecto?

**Comment by flickerapps** [comment]
Gracias @ADelRosarioH por tu opinion! Te invitamos a probar el framework y que te unas a la comunidad hispana del proyecto.

**Comment by flickerapps** [comment]
@reneolivo Que tal bro! Flicker.js es un nuevo framework web para node.js desarollado por este servidor, este proyecto empezo como una tarea personal para reforzar mis conocimientos pero ahora quiero expandirlo y convertirlo en un proyecto desarrollado por y para la comunidad hispana, de modo que la documentacion y desarrolladores hablemos el mismo idioma, ademas de pornersela un poquito mas facil a los que empiezan con javascript/node, te invito a echarle un vistazo al repositorio y me digas que tal te parece la idea.

**Comment by ranfis** [comment]
@flickerapps No se porque soy parte de la organizacion :laughing:, pero Flicker.js esta bien. Pienso que no es buena idea cambiarle el nombre para una version "hispana".

**Comment by flickerapps** [comment]
@ranfis Que tal bro! xd Los invite a la organizacion para mostrarles el proyecto, y lo del nombre es para que todo sea en español pero veo que Flicker suena bien comoquiera, pero mi idea es eliminar el  repositorio en ingles y quedarnos con el español, pero mientras crece solo es parte de un fork al que se me ocurrio llamarle (version "hispana").

**Comment by rmariuzzo** [comment]
Pienso que no es buena idea traducir el nombre.
